config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :cart, only: [:show] do
    put 'add/:product_id/:quantity/:price', to: 'carts#add', as: :add_to
    put 'remove/:product_id', to: 'carts#remove', as: :remove_from
  end

  devise_for :users, path_names: { sign_in: 'login', sign_up: 'register', sign_out: 'logout' }
  root 'products#index'
  resources :products
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, :price, presence: true

  def cart_action(_current_user_id)
    "Add to"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

  def cart_count
    @quantity = []
    keys_quantity = $redis.keys("cart#{id}:product*:quantity")
    keys_quantity.map { |key| @quantity << $redis.get(key).to_i }
    @quantity.reduce(0, :+)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_param|
      user_param.permit(:name, :email, :password, :password_confirmation)
    end

    devise_parameter_sanitizer.permit(:account_update) do |user_param|
      user_param.permit(:name)
    end
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    all_products(current_user_cart)
    @cart_products = Array.new
    @cart_products.concat Product.find(@cart_ids)
  end

  def add
    unless product?(params[:product_id])
      new_quantity((params[:product_id]), params[:quantity].to_i)
    else
      add_product(params[:product_id])
      add_quantity(params[:product_id], params[:quantity])
      add_price(params[:product_id], params[:price])
    end
    render json: current_user.cart_count, status: 200
  end

  def remove
    destroy_redis("#{current_user_cart_product}#{params[:product_id]}:quantity")
    destroy_redis("#{current_user_cart_product}#{params[:product_id]}")
    destroy_redis("#{current_user_cart_product}#{params[:product_id]}:price")
    render json: current_user.cart_count, status: 200
  end

  private

  def current_user_cart
    "cart#{current_user.id}"
  end

  def current_user_cart_product
    "#{current_user_cart}:product"
  end 

  def add_price(product_id, price) 
    create_redis("#{current_user_cart_product}#{product_id}:price", price)
    $redis.expire("#{current_user_cart_product}#{product_id}:price", 2.days)
  end

  def current_quantity(product_id)
    show_redis("#{current_user_cart_product}#{product_id}:quantity").to_i
  end

  def add_quantity(product_id, quantity)
    create_redis("#{current_user_cart_product}#{product_id}:quantity", quantity)
    $redis.expire("#{current_user_cart_product}#{product_id}:quantity", 2.days)
  end

  def remove_quantity(product_id)
    destroy_redis("#{current_user_cart_product}#{product_id}:quantity")
  end

  def new_quantity(product_id, quantity)
    current_quantity = current_quantity(product_id)
    total_quantity = current_quantity + quantity
    remove_quantity(product_id)
    add_quantity(product_id, quantity)
  end

  def product?(product_id)
    show_redis("#{current_user_cart_product}#{product_id}").nil?
  end

  def all_products(cart_product)
    @cart_ids = Array.new
    @keys = Array.new
    keys_product = Array.new
    keys_product.concat(search_redis("#{current_user_cart_product}*")).each { |key| @keys << /#{current_user_cart_product}\d/.match(key).to_s }
    @keys.uniq.map { |key| @cart_ids << show_redis(key.to_s) }
  end

  def add_product(product_id)
    create_redis("#{current_user_cart_product}#{product_id}", product_id)
    $redis.expire("#{current_user_cart_product}#{product_id}", 2.days)
  end

  def create_redis(key,value)
    $redis.set(key.to_s,value)
  end

  def show_redis(key)
    $redis.get(key.to_s)
  end

  def search_redis(key)
    $redis.keys(key.to_s)
  end

  def destroy_redis(key)
    $redis.del(key.to_s)
  end

end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :edit, :update, :show, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
    @cart_action = @product.cart_action current_user.try :id
  end

  def new
    @product = Product.new
  end

  def edit; end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: t('message.product.create') }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: t('message.product.update') }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: t('message.product.destroy') }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type
    when :success
      "alert-success"
    when :error
      "alert-error"
    when :alert
      "alert-block"
    when :notice
      "alert-info"
    else
      flash_type.to_s
    end
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
  def quantity(user_id, product_id)
    quantity = $redis.get("cart#{user_id}:product#{product_id}:quantity")
    if quantity.nil?
      "1"
    else
      quantity
    end
  end

  def subtotal(user_id, product_id, price)
    quantity = $redis.get("cart#{user_id}:product#{product_id}:quantity")
    price.to_d * quantity.to_f
  end

  def total_calculator(user_id, product_id, price)
    @total += subtotal(user_id, product_id, price)
  end

  def check_price(user_id, product_id, price)
    old_price = $redis.get("cart#{user_id}:product#{product_id}:price")
    flash[:alert] = 'The price has changed since your last visit' unless price == old_price
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/carts/show.html.erb
  <h1>My Cart</h1>
  <p>You've selected <span class="cart-count">
  	<%= current_user.cart_count %></span> products</p>

  <table id="cart" class="table table-hover table-condensed">
            <thead>
            <tr>
              <th style="width:50%">Name</th>
              <th style="width:10%">Price</th>
              <th style="width:8%">Quantity</th>
              <th style="width:22%" class="text-center">Subtotal</th>
              <th style="width:10%"></th>
            </tr>
          </thead>
          <tbody>
           <% @cart_products.each do |product| %> 
            <tr>
              <td data-th="Product">
                <div class="row">
                  <div class="col-sm-2 hidden-xs"><img src="http://placehold.it/100x100" alt="..." class="img-responsive"/></div>
                  <div class="col-sm-10">
                    <h4 class="nomargin"><%= product.name %></h4> 
                  </div>
                </div>
              </td>
              <td data-th="Price" class="price">$<%= product.price %></td>
              <td data-th="Quantity">
                <input type="number" class="form-control text-center" value="<%= quantity(current_user.id, product.id) %>">
              </td>
              <td data-th="Subtotal" class="text-center">$<span id="subtotal"><%= subtotal(current_user.id, product.id, product.price) %></span></td>
              <td class="actions" data-th="">
                <button class="btn btn-info btn-sm"><i class="fa fa-refresh"></i></button>
                <%=link_to "", class: "btn btn-danger btn-sm", 
                   data: {target: @cart_action, removeUrl: remove_from_cart_path(product.id) } do %>
                    <i class="fa fa-trash-o"></i>
                    <span><%=@cart_action%></span>
                <% end %>              
              </td>
            </tr>
          <% end %>
          </tbody>
          <tfoot> 
            <tr>
              <td><a href="/" class="btn btn-warning"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
              <td colspan="2" class="hidden-xs"></td>
              <td class="hidden-xs text-center"><strong>Total $<span id="total"></span></strong></td>
              <td><a href="#" id="checkout" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
            </tr>
          </tfoot>
        </table>

app/views/layouts/_alerts.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-primary">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">CartTest</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to 'Products', products_path %> </li>
        <% if signed_in? %>
          <li><%=link_to "Hello, #{current_user.name}", edit_user_registration_path%></li>
          <li>
            <%= link_to cart_path do %>
              <i class="fa fa-shopping-cart"></i>
              My Cart
              (<span class="cart-count"><%= current_user.cart_count %></span>)
            <% end %>
          </li>
          <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
        <% else %>
          <li><%=link_to "Register", new_user_registration_path%></li>
          <li><%=link_to "Login", new_user_session_path%></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  </head>

  <body>

    <%= render 'layouts/header' %>

  
    <%= render partial: "layouts/alerts", flash: flash %> 

    <div class="container">
    <%= yield %>    	
    </div>

    <footer class="row">
        <hr />
        <p>TestCart 2017 &copy;</p>
    </footer>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products</h1>

  <div class="row">
    <% @products.each do |product| %>
    <%= link_to product_path(product) do %>
    <div class="col-md-4">
      <div class="col-md-12">
        <%= image_tag 'rails', width: '120', height: '120' %>
      </div>

      <div class="col-md-12">
        
        <h5><%= product.name %></h5>
      </div>

      <div class="col-md-12">
        <p>$<%= product.price %></p>
      </div>

    </div>
    <% end %>
    <% end %>
  </div>
  <br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="col-md-4">
  <div class="col-md-12">
    <%= image_tag 'rails', width: '120', height: '120' %>
  </div>

  <div class="col-md-12">

    <h4><%= @product.name  %></h4>
  </div>


  <div class="col-md-12">
    <p id="product_price"><%= @product.price %></p>
  </div>


  <div class="col-md-12">
  Quantidade: <input type="number" id="product_quantity" class="text-center" value="<%= quantity(current_user.id, @product.id) %>">
  </div>
  <div class="col-md-12">

    <% if signed_in? %>
    <%=link_to "", class: "btn btn-primary", 
    data: {target: @cart_action, addUrl: add_to_cart_path(@product, quantity: 1, price: 2)} do %>
    <i class="fi-shopping-cart"></i>
    <span><%=@cart_action%></span> Cart
    <% end %>
    <% end %>

  </div>

</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to 'Back', products_path %>
  </div>
</div>